name: food_saver
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

#--------------- PACKAGES ------------------#
dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  capped_progress_indicator: ^0.0.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dio: ^5.4.3+1
  easy_refresh: ^3.4.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.1
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  get_it: ^7.6.7
  get_storage: ^2.1.1
  http: ^1.1.0
  iconsax: ^0.0.8
  image_picker: ^1.0.8
  intl: ^0.18.1
  logger: ^2.0.1
  provider: ^6.1.2
  readmore: ^2.2.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lottie: ^2.7.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/IMG-20240520-WA0012.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/Food Saver logo.jpg
    - assets/logos/Food Saver logo2.jpg
    - assets/icons/brands/
    - assets/images/content/user.png
    - assets/images/banners/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/categories/Bakery.jpg
    - assets/categories/Deserts.jpg
    - assets\categories\Grocery.jpg
    - assets\categories\meals.jpg
    - assets/images/foodsaving card.jpeg
    - assets/images/cupcake.jpg
    - assets/logos/IMG-20240520-WA0012.png
    - assets/splash_screen/VID 20240516 WA0043.json
    - assets/splash_screen/VID 20240516 WA0044.json
    - assets/splash_screen/WhatsApp Video 2024 06 08 at 3.39.02 PM (1).json
    - assets/images/right sign.png
    - assets/icons/robot.png
    - assets/icons/robot (1).png

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
    - family: Ubuntu Sans
      fonts:
        - asset: assets/fonts/UbuntuSans_Condensed-Medium.ttf
          weight: 400
